generator_ckpt: ./ckpts/Wan21/Action2V/ar_diffusion_tf/model.pt
generator_grad:
  model: true
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
generator_task: causal_video
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
mixed_precision: true
seed: 0
wandb_host: https://api.wandb.ai
wandb_key: <your_wandb_key>
wandb_entity: <your_wandb_entity>
wandb_project: causal_ode_camera
wandb_name: causal_ode_camera
sharding_strategy: hybrid_full
lr: 2.0e-06
beta1: 0.9
beta2: 0.999
data_path: ./dataset/Wan21/Action2V/ode_lmdb
batch_size: 1
log_iters: 1000
trainer: camera_ode
gradient_checkpointing: true
num_frame_per_block: 4
ema_weight: 0.99
ema_start_step: 200
use_camera: true
model_kwargs:
  timestep_shift: 5.0
  local_attn_size: 20
  use_camera: true
